services:
  n8n-workbench-editor:
    image: n8nio/n8n
    restart: unless-stopped
    container_name: n8n-editor
    ports:
      - 5678:5678
    volumes:
      - ./.volumes/n8n:/home/node/.n8n
    networks:
      - n8n-workbench-network
    env_file:
      - ./.env
  n8n-workbench-worker:
    image: n8nio/n8n
    restart: unless-stopped
    container_name: n8n-worker
    ports:
      - 5677:5678
    volumes:
      - ./.volumes/n8n:/home/node/.n8n
    networks:
      - n8n-workbench-network
    env_file:
      - ./.env
    command: worker
  n8n-workbench-webhook:
    image: n8nio/n8n
    restart: unless-stopped
    container_name: n8n-webhook
    ports:
      - 5676:5678
    volumes:
      - ./.volumes/n8n:/home/node/.n8n
    networks:
      - n8n-workbench-network
    env_file:
      - ./.env
    command: webhook
  n8n-pgsql:
    image: ankane/pgvecto
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${DB_POSTGRESDB_USER}
      - POSTGRES_PASSWORD=${DB_POSTGRESDB_PASSWORD}
      - POSTGRES_DB=${DB_POSTGRESDB_DATABASE}
    volumes:
      - ./.volumes/postgres:/var/lib/postgresql/data
    networks:
      - n8n-workbench-network
  n8n-redis:
    image: redis:alpine
    restart: unless-stopped
    ports:
      - 6379:6379
    volumes:
      - ./.volumes/redis:/data
    networks:
      - n8n-workbench-network
networks:
  n8n-workbench-network:
    driver: bridge
